connect(db.sqlit3)
INSERT INTO shop_province(id,name,slug) VALUES (1,'آذربایجان شرقی','آذربایجان-شرقی');
INSERT INTO shop_province(id,name,slug) VALUES (2,'آذربایجان غربی','آذربایجان-غربی');
INSERT INTO shop_province(id,name,slug) VALUES (3,'اردبیل','اردبیل');
INSERT INTO shop_province(id,name,slug) VALUES (4,'اصفهان','اصفهان');
INSERT INTO shop_province(id,name,slug) VALUES (5,'البرز','البرز');
INSERT INTO shop_province(id,name,slug) VALUES (6,'ایلام','ایلام');
INSERT INTO shop_province(id,name,slug) VALUES (7,'بوشهر','بوشهر');
INSERT INTO shop_province(id,name,slug) VALUES (8,'تهران','تهران');
INSERT INTO shop_province(id,name,slug) VALUES (9,'چهارمحال و بختیاری','چهارمحال-بختیاری');
INSERT INTO shop_province(id,name,slug) VALUES (10,'خراسان جنوبی','خراسان-جنوبی');
INSERT INTO shop_province(id,name,slug) VALUES (11,'خراسان رضوی','خراسان-رضوی');
INSERT INTO shop_province(id,name,slug) VALUES (12,'خراسان شمالی','خراسان-شمالی');
INSERT INTO shop_province(id,name,slug) VALUES (13,'خوزستان','خوزستان');
INSERT INTO shop_province(id,name,slug) VALUES (14,'زنجان','زنجان');
INSERT INTO shop_province(id,name,slug) VALUES (15,'سمنان','سمنان');
INSERT INTO shop_province(id,name,slug) VALUES (16,'سیستان و بلوچستان','سیستان-بلوچستان');
INSERT INTO shop_province(id,name,slug) VALUES (17,'فارس','فارس');
INSERT INTO shop_province(id,name,slug) VALUES (18,'قزوین','قزوین');
INSERT INTO shop_province(id,name,slug) VALUES (19,'قم','قم');
INSERT INTO shop_province(id,name,slug) VALUES (20,'کردستان','کردستان');
INSERT INTO shop_province(id,name,slug) VALUES (21,'کرمان','کرمان');
INSERT INTO shop_province(id,name,slug) VALUES (22,'کرمانشاه','کرمانشاه');
INSERT INTO shop_province(id,name,slug) VALUES (23,'کهگیلویه و بویراحمد','کهگیلویه-بویراحمد');
INSERT INTO shop_province(id,name,slug) VALUES (24,'گلستان','گلستان');
INSERT INTO shop_province(id,name,slug) VALUES (25,'لرستان','لرستان');
INSERT INTO shop_province(id,name,slug) VALUES (26,'گیلان','گیلان');
INSERT INTO shop_province(id,name,slug) VALUES (27,'مازندران','مازندران');
INSERT INTO shop_province(id,name,slug) VALUES (28,'مرکزی','مرکزی');
INSERT INTO shop_province(id,name,slug) VALUES (29,'هرمزگان','هرمزگان');
INSERT INTO shop_province(id,name,slug) VALUES (30,'همدان','همدان');
INSERT INTO shop_province(id,name,slug) VALUES (31,'یزد','یزد');