from django.urls import path
from .views import *
urlpatterns = [
    path('',HomePage.as_view(),name = 'HomePage'),
    path('HomePage/',HomePage.as_view(),name = 'HomePage'),
    path('ContactUs/',ContactUs.as_view(),name = 'ContactUs'),
    path('AboutUs/',AboutUs.as_view(),name = 'AboutUs'),
    path('Profile/<int:pk>/',ProfileView.as_view(),name = 'Profile'),
    path('ProfileEdit/<int:pk>/',ProfileEdit.as_view(),name = 'ProfileEdit'),
    path('ProductView/',ProductView.as_view(),name='ProductView'),
    path('ProductCreate/<int:pk>/',ProductCreate.as_view(),name = 'ProductCreate'),
    path('ProductEdit/<int:pk>/',ProductEdit.as_view(),name = 'ProductEdit'), 
    path('ProductDelete/<int:pk>/',ProductDelete.as_view(),name = 'ProductDelete'),
    path('ProductDetail/<int:pk>/',ProductDetail.as_view(),name = 'ProductDetail'), 
    path('Search/>',Search.as_view(), name='Search'),
    path('CategoryView/',CategoryView.as_view(),name='CategoryView'),
    path('CategoryDetail/<int:pk>/',CategoryDetail.as_view(),name='CategoryDetail'),
    path('CategoryCreate/',CategoryCreate.as_view(), name='CategoryCreate'),
    path('CategoryEdit/<int:pk>/',CategoryEdit.as_view(),name='CategoryEdit'),
    path('CategoryDelete/<int:pk>/',CategoryDelete.as_view(),name='CategoryDelete'),
    path('SupplierView/',SupplierView.as_view(),name='SupplierView'),
    path('SupplierCreate/',SupplierCreate.as_view(),name='SupplierCreate'),
    path('SupplierEdit/<int:pk>/',SupplierEdit.as_view(),name='SupplierEdit'),
    path('SupplierDelete/<int:pk>/',SupplierDelete.as_view(),name='SupplierDelete'),
    path('SupplierDetail/<int:pk>/',SupplierDetail.as_view(),name='SupplierDetail'),
    path('InventoryView/',InventoryView.as_view(),name='InventoryView'),
    path('InventoryCreate/',InventoryCreate.as_view(),name='InventoryCreate'),
    path('InventoryrEdit/<int:pk>/',InventoryEdit.as_view(),name='InventoryEdit'),
    path('InventoryDelete/<int:pk>/',InventoryDelete.as_view(),name='InventoryDelete'),
    path('InventoryDetail/<int:pk>/',InventoryDetail.as_view(),name='InventoryDetail'),
    path('InventoryProduct/',InventoryProductView.as_view(),name='InventoryProduct'),
    path('InventoryProductDetail/<int:pk>/',InventoryProductDetail.as_view(),name='InventoryProductDetail'),
    path('InventoryProductCreate/',InventoryProductCreate.as_view(),name='InventoryProductCreate'),
    path('InventoryProductEdit/<int:pk>/',InventoryProductEdit.as_view(),name='InventoryProductEdit'),
    path('InventoryProductDelete/<int:pk>/',InventoryProductDelete.as_view(),name='InventoryProductDelete'),
    path('addtocart/', addToCart, name='addtocart'),
    path('Cart/<int:pk>/',CartDetailView.as_view(), name='CartView'),
    path('OrderCreate/',orderCreate,name='ordercreate'),
    path('CartEdit/<int:cartItemId>/',updateCart,name='updatcart'),
    path('CartDelete/<int:cartItemId>/',deletFromCart,name='deletefromcart'),
    path('Order/',OrderListVeiw.as_view(),name='orders'),
    path('Order/update/<int:pk>/',OrderUpdate.as_view(),name='orderupdate')
    
]
