from django.urls import path
from django.views.generic import RedirectView

from .views import (
    AboutUs,
    CartDetailView,
    CategoryCreate,
    CategoryDelete,
    CategoryDetail,
    CategoryEdit,
    CategoryView,
    ContactUs,
    HomePage,
    InventoryCreate,
    InventoryDelete,
    InventoryDetail,
    InventoryEdit,
    InventoryProductCreate,
    InventoryProductDelete,
    InventoryProductDetail,
    InventoryProductEdit,
    InventoryProductView,
    InventoryView,
    OrderListView,
    OrderUpdate,
    ProductCreate,
    ProductDelete,
    ProductDetail,
    ProductEdit,
    ProductView,
    SearchView,
    SupplierCreate,
    SupplierDelete,
    SupplierDetail,
    SupplierEdit,
    SupplierView,
    add_to_cart,
    create_order,
    delete_from_cart,
    update_cart,
)


urlpatterns = [
    path('', HomePage.as_view(), name='HomePage'),
    path('HomePage/', HomePage.as_view(), name='HomePage'),
    path('ContactUs/', ContactUs.as_view(), name='ContactUs'),
    path('AboutUs/', AboutUs.as_view(), name='AboutUs'),
    path(
        'Profile/<int:pk>/',
        RedirectView.as_view(pattern_name='accounts:profile', permanent=False),
        name='Profile',
    ),
    path(
        'ProfileEdit/<int:pk>/',
        RedirectView.as_view(pattern_name='accounts:profile-edit', permanent=False),
        name='ProfileEdit',
    ),
    path('ProductView/', ProductView.as_view(), name='ProductView'),
    path('ProductCreate/', ProductCreate.as_view(), name='ProductCreate'),
    path('ProductEdit/<int:pk>/', ProductEdit.as_view(), name='ProductEdit'),
    path('ProductDelete/<int:pk>/', ProductDelete.as_view(), name='ProductDelete'),
    path('ProductDetail/<int:pk>/', ProductDetail.as_view(), name='ProductDetail'),
    path('Search/', SearchView.as_view(), name='Search'),
    path('CategoryView/', CategoryView.as_view(), name='CategoryView'),
    path('CategoryDetail/<int:pk>/', CategoryDetail.as_view(), name='CategoryDetail'),
    path('CategoryCreate/', CategoryCreate.as_view(), name='CategoryCreate'),
    path('CategoryEdit/<int:pk>/', CategoryEdit.as_view(), name='CategoryEdit'),
    path('CategoryDelete/<int:pk>/', CategoryDelete.as_view(), name='CategoryDelete'),
    path('SupplierView/', SupplierView.as_view(), name='SupplierView'),
    path('SupplierCreate/', SupplierCreate.as_view(), name='SupplierCreate'),
    path('SupplierEdit/<int:pk>/', SupplierEdit.as_view(), name='SupplierEdit'),
    path('SupplierDelete/<int:pk>/', SupplierDelete.as_view(), name='SupplierDelete'),
    path('SupplierDetail/<int:pk>/', SupplierDetail.as_view(), name='SupplierDetail'),
    path('InventoryView/', InventoryView.as_view(), name='InventoryView'),
    path('InventoryCreate/', InventoryCreate.as_view(), name='InventoryCreate'),
    path('InventoryEdit/<int:pk>/', InventoryEdit.as_view(), name='InventoryEdit'),
    path('InventoryDelete/<int:pk>/', InventoryDelete.as_view(), name='InventoryDelete'),
    path('InventoryDetail/<int:pk>/', InventoryDetail.as_view(), name='InventoryDetail'),
    path('InventoryProduct/', InventoryProductView.as_view(), name='InventoryProduct'),
    path('InventoryProductDetail/<int:pk>/', InventoryProductDetail.as_view(), name='InventoryProductDetail'),
    path('InventoryProductCreate/', InventoryProductCreate.as_view(), name='InventoryProductCreate'),
    path('InventoryProductEdit/<int:pk>/', InventoryProductEdit.as_view(), name='InventoryProductEdit'),
    path('InventoryProductDelete/<int:pk>/', InventoryProductDelete.as_view(), name='InventoryProductDelete'),
    path('addtocart/', add_to_cart, name='add_to_cart'),
    path('Cart/<int:pk>/', CartDetailView.as_view(), name='cart_detail'),
    path('OrderCreate/', create_order, name='order_create'),
    path('CartEdit/<int:cart_item_id>/', update_cart, name='cart_update'),
    path('CartDelete/<int:cart_item_id>/', delete_from_cart, name='cart_delete'),
    path('Order/', OrderListView.as_view(), name='order_list'),
    path('Order/update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
]
