# Generated by Django 4.2.1 on 2023-07-02 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_province_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '0999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{11,11}$')]),
        ),
    ]
