# Generated by Django 4.2.2 on 2023-07-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='province',
        ),
    ]
