# Generated by Django 4.2.1 on 2023-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summaries',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
