# Generated by Django 4.2.2 on 2026-04-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_summaries"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="summaries",
            new_name="summary",
        ),
    ]
