# Generated by Django 4.2.1 on 2023-05-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_description_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titles',
            new_name='title',
        ),
    ]
