# Generated by Django 4.2.1 on 2023-06-30 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_inventory_address_inventory_phone_supplier_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be like 09371889805', regex='^\\+?1?\\d{11,11}$')]),
        ),
    ]
