# Generated by Django 4.2.2 on 2023-07-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_city'),
        ('Shop', '0018_alter_supplier_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
