# Generated by Django 4.2.2 on 2026-04-03 12:00

from decimal import Decimal

from django.db import migrations, models


def populate_orderitem_price_snapshot(apps, schema_editor):
    OrderItem = apps.get_model("Shop", "OrderItem")

    for order_item in OrderItem.objects.select_related("product").all():
        unit_price = order_item.product.price or Decimal("0.00")
        order_item.unit_price = unit_price
        order_item.line_total = unit_price * order_item.quantity
        order_item.save(update_fields=["unit_price", "line_total"])


def clear_orderitem_price_snapshot(apps, schema_editor):
    OrderItem = apps.get_model("Shop", "OrderItem")
    OrderItem.objects.update(unit_price=None, line_total=None)


class Migration(migrations.Migration):

    dependencies = [
        ("Shop", "0023_alter_order_address_alter_order_province_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_send",
            new_name="is_sent",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(
            populate_orderitem_price_snapshot,
            reverse_code=clear_orderitem_price_snapshot,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
